### ISSUE TITLE
Choix plusieurs motifs

### ISSUE THREAD

**Issue by Marvel63** [Faylixe/covidcert#1]
Bonjour et un grand bravo pour ce remarquable boulot.
Est-ce qu'il est possible de saisir plusieurs valeurs dans "reason"? si oui sous quelle forme?

**Comment by AlainProvist** [comment]
> 
> 
> Bonjour et un grand bravo pour ce remarquable boulot.
> Est-ce qu'il est possible de saisir plusieurs valeurs dans "reason"? si oui sous quelle forme?

Je ne suis pas sûr que cocher plusieurs cases soit la bonne chose à faire dans le cas d'un contrôle de police. Il me semble bien que le site du gouvernement permet cela, mais dans la réalité on ne fait que rarement plusieurs motifs de sortie au même moment. On enchaîne plutôt les motifs un à un lors d'une même sortie, et pour cela, on peut très bien générer les autorisations de sortie successivement ou même à l'avance si on le désire.

**Comment by AlainProvist** [comment]
Mais pour répondre à la question, ce n'est pas possible avec la version actuelle. Il faudrait pour cela définir la raison comme un bitfield afin de permettre des choix multiples.
